# Generated by Django 5.1.3 on 2024-12-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_purchase_rental"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0)),
                ("rented_quantity", models.PositiveIntegerField(default=0)),
                ("purchased_quantity", models.PositiveIntegerField(default=0)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.book"
                    ),
                ),
            ],
        ),
    ]
