# Generated by Django 5.1.3 on 2024-12-09 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0003_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Whislist",
            new_name="Wishlist",
        ),
    ]
